// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb-OZ98U1XYo9Ku1d4ZwEiYQV1RoBm15o',
    appId: '1:103061184777:android:4791a044758104fe27f3d8',
    messagingSenderId: '103061184777',
    projectId: 'hermifyapp',
    storageBucket: 'hermifyapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7emrgem10rbF8iXvJhfIWHutjuuptZbo',
    appId: '1:103061184777:ios:cbec6d43f601e84227f3d8',
    messagingSenderId: '103061184777',
    projectId: 'hermifyapp',
    storageBucket: 'hermifyapp.firebasestorage.app',
    androidClientId: '103061184777-bfachiipk1ovpd00en9v8oag67eh96q6.apps.googleusercontent.com',
    iosClientId: '103061184777-7mdlsoimibublk57o4dluqtmk07ffh78.apps.googleusercontent.com',
    iosBundleId: 'com.snt.hermifyapp',
  );

}